config/routes.rb
Rails.application.routes.draw do
  root 'profiles#index'
  resources :profiles
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
      redirect_to root_path
  end

  private

  def profile_params
    params.require(:profile).permit([:first_name, :last_name, :email])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RentPseudo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield 

app/views/profiles/_form.html.slim
.form-overlay
  = simple_form_for :profile, url: profiles_path, method: :post do |f|
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.submit "Submit"

app/views/profiles/_header.html.slim
.navbar.navbar-default
  .center
    h1= "Zipqode"
  .center
    p= "Get your next home"

app/views/profiles/index.html.slim
= render 'header'
#wallpaper
  img src="/home.jpg" alt="Home"
= render 'form'